package ender.dwmod.datagen;

import ender.dwmod.DwMod;
import ender.dwmod.block.BlockInit;
import ender.dwmod.block.tardis.EndoshellBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;

/**
 * Single model provider for this mod.
 *
 * Fabric registers all FabricModelProvider instances under the same provider name
 * ("<modid>/Model Definitions"), so we must keep everything in one class to avoid
 * "Duplicate provider" errors during datagen.
 */
public class DwModModelProvider extends FabricModelProvider {

    private static final ResourceLocation EMPTY_MODEL = ResourceLocation.fromNamespaceAndPath(DwMod.MOD_ID, "block/empty");

    /**
     * Single source of truth for all simple "building blocks".
     * Add new blocks here once; both blockstate/model and item model generation will follow.
     */
    public static final Block[] BUILDING_BLOCKS = {
        EndoshellBlocks.TARDIS_DEFAULT_FLOOR
    };

    public DwModModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators blockStateModelGenerator) {
        // Barrier-like / invisible blocks
        generateEmptyBlockState(blockStateModelGenerator, BlockInit.DEFAULT_CONSOLE_INTERACT);
        generateEmptyBlockState(blockStateModelGenerator, BlockInit.DEFAULT_CONSOLE);

        // Building blocks (simple cube-all)
        for (Block block : BUILDING_BLOCKS) {
            blockStateModelGenerator.createTrivialCube(block);
        }
    }

    private static void generateEmptyBlockState(BlockModelGenerators blockStateModelGenerator, Block block) {
        blockStateModelGenerator.blockStateOutput.accept(
            BlockModelGenerators.createSimpleBlock(block, EMPTY_MODEL)
        );
    }

    @Override
    public void generateItemModels(ItemModelGenerators itemModelGenerator) {
        // Block-items that should parent the block model are generated by BuildingBlockItemModelProvider.
    }
}
